# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/debian/.devcontainer/base.Dockerfile

# [Choice] Debian version (use bullseye or stretch on local arm64/Apple Silicon): bullseye, buster, stretch
ARG VARIANT="buster"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends build-essential mingw-w64 binutils

USER vscode
ENV CHOOSENIM_NO_ANALYTICS 1
ENV PATH $HOME/.nimble/bin:$PATH
RUN echo 'export PATH="$HOME/.nimble/bin:$PATH"' >> ~/.profile